title: UWRIGHT Blog
author: DJwrighTalker
description: Synthesized insight from 5 7 5 in 8 8 1 0 1.
baseurl: ""
url: "https://uwrightlabs.com"
theme: minima
plugins:
  - jekyll-feed

collections:
  blog:
    output: true
    permalink: /blog/:title/
  music:
    output: true
    permalink: /music/:title/
  projects:
    output: true
    permalink: /projects/:title/
